# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zrh/SURFGPU-1.2.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zrh/SURFGPU-1.2.1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/local/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zrh/SURFGPU-1.2.1/CMakeFiles /home/zrh/SURFGPU-1.2.1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zrh/SURFGPU-1.2.1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named surf

# Build rule for target.
surf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 surf
.PHONY : surf

# fast build rule for target.
surf/fast:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/build
.PHONY : surf/fast

cuda/getMatchesGPU.o: cuda/getMatchesGPU.cpp.o
.PHONY : cuda/getMatchesGPU.o

# target to build an object file
cuda/getMatchesGPU.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/getMatchesGPU.cpp.o
.PHONY : cuda/getMatchesGPU.cpp.o

cuda/getMatchesGPU.i: cuda/getMatchesGPU.cpp.i
.PHONY : cuda/getMatchesGPU.i

# target to preprocess a source file
cuda/getMatchesGPU.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/getMatchesGPU.cpp.i
.PHONY : cuda/getMatchesGPU.cpp.i

cuda/getMatchesGPU.s: cuda/getMatchesGPU.cpp.s
.PHONY : cuda/getMatchesGPU.s

# target to generate assembly for a file
cuda/getMatchesGPU.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/getMatchesGPU.cpp.s
.PHONY : cuda/getMatchesGPU.cpp.s

cuda/helper_funcs.o: cuda/helper_funcs.cpp.o
.PHONY : cuda/helper_funcs.o

# target to build an object file
cuda/helper_funcs.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/helper_funcs.cpp.o
.PHONY : cuda/helper_funcs.cpp.o

cuda/helper_funcs.i: cuda/helper_funcs.cpp.i
.PHONY : cuda/helper_funcs.i

# target to preprocess a source file
cuda/helper_funcs.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/helper_funcs.cpp.i
.PHONY : cuda/helper_funcs.cpp.i

cuda/helper_funcs.s: cuda/helper_funcs.cpp.s
.PHONY : cuda/helper_funcs.s

# target to generate assembly for a file
cuda/helper_funcs.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/helper_funcs.cpp.s
.PHONY : cuda/helper_funcs.cpp.s

cuda/strerror_cudpp.o: cuda/strerror_cudpp.cpp.o
.PHONY : cuda/strerror_cudpp.o

# target to build an object file
cuda/strerror_cudpp.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/strerror_cudpp.cpp.o
.PHONY : cuda/strerror_cudpp.cpp.o

cuda/strerror_cudpp.i: cuda/strerror_cudpp.cpp.i
.PHONY : cuda/strerror_cudpp.i

# target to preprocess a source file
cuda/strerror_cudpp.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/strerror_cudpp.cpp.i
.PHONY : cuda/strerror_cudpp.cpp.i

cuda/strerror_cudpp.s: cuda/strerror_cudpp.cpp.s
.PHONY : cuda/strerror_cudpp.s

# target to generate assembly for a file
cuda/strerror_cudpp.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/cuda/strerror_cudpp.cpp.s
.PHONY : cuda/strerror_cudpp.cpp.s

fasthessian.o: fasthessian.cpp.o
.PHONY : fasthessian.o

# target to build an object file
fasthessian.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/fasthessian.cpp.o
.PHONY : fasthessian.cpp.o

fasthessian.i: fasthessian.cpp.i
.PHONY : fasthessian.i

# target to preprocess a source file
fasthessian.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/fasthessian.cpp.i
.PHONY : fasthessian.cpp.i

fasthessian.s: fasthessian.cpp.s
.PHONY : fasthessian.s

# target to generate assembly for a file
fasthessian.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/fasthessian.cpp.s
.PHONY : fasthessian.cpp.s

getSurfFeaGPU.o: getSurfFeaGPU.cpp.o
.PHONY : getSurfFeaGPU.o

# target to build an object file
getSurfFeaGPU.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/getSurfFeaGPU.cpp.o
.PHONY : getSurfFeaGPU.cpp.o

getSurfFeaGPU.i: getSurfFeaGPU.cpp.i
.PHONY : getSurfFeaGPU.i

# target to preprocess a source file
getSurfFeaGPU.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/getSurfFeaGPU.cpp.i
.PHONY : getSurfFeaGPU.cpp.i

getSurfFeaGPU.s: getSurfFeaGPU.cpp.s
.PHONY : getSurfFeaGPU.s

# target to generate assembly for a file
getSurfFeaGPU.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/getSurfFeaGPU.cpp.s
.PHONY : getSurfFeaGPU.cpp.s

integral.o: integral.cpp.o
.PHONY : integral.o

# target to build an object file
integral.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/integral.cpp.o
.PHONY : integral.cpp.o

integral.i: integral.cpp.i
.PHONY : integral.i

# target to preprocess a source file
integral.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/integral.cpp.i
.PHONY : integral.cpp.i

integral.s: integral.cpp.s
.PHONY : integral.s

# target to generate assembly for a file
integral.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/integral.cpp.s
.PHONY : integral.cpp.s

ipoint.o: ipoint.cpp.o
.PHONY : ipoint.o

# target to build an object file
ipoint.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.cpp.o
.PHONY : ipoint.cpp.o

ipoint.i: ipoint.cpp.i
.PHONY : ipoint.i

# target to preprocess a source file
ipoint.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.cpp.i
.PHONY : ipoint.cpp.i

ipoint.s: ipoint.cpp.s
.PHONY : ipoint.s

# target to generate assembly for a file
ipoint.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/ipoint.cpp.s
.PHONY : ipoint.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/main.cpp.s
.PHONY : main.cpp.s

surf.o: surf.cpp.o
.PHONY : surf.o

# target to build an object file
surf.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.cpp.o
.PHONY : surf.cpp.o

surf.i: surf.cpp.i
.PHONY : surf.i

# target to preprocess a source file
surf.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.cpp.i
.PHONY : surf.cpp.i

surf.s: surf.cpp.s
.PHONY : surf.s

# target to generate assembly for a file
surf.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/surf.cpp.s
.PHONY : surf.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/surf.dir/build.make CMakeFiles/surf.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... surf"
	@echo "... cuda/getMatchesGPU.o"
	@echo "... cuda/getMatchesGPU.i"
	@echo "... cuda/getMatchesGPU.s"
	@echo "... cuda/helper_funcs.o"
	@echo "... cuda/helper_funcs.i"
	@echo "... cuda/helper_funcs.s"
	@echo "... cuda/strerror_cudpp.o"
	@echo "... cuda/strerror_cudpp.i"
	@echo "... cuda/strerror_cudpp.s"
	@echo "... fasthessian.o"
	@echo "... fasthessian.i"
	@echo "... fasthessian.s"
	@echo "... getSurfFeaGPU.o"
	@echo "... getSurfFeaGPU.i"
	@echo "... getSurfFeaGPU.s"
	@echo "... integral.o"
	@echo "... integral.i"
	@echo "... integral.s"
	@echo "... ipoint.o"
	@echo "... ipoint.i"
	@echo "... ipoint.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... surf.o"
	@echo "... surf.i"
	@echo "... surf.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

